# yaml format

- id: 16
  name: move
  params:
    - pos_x: int
    - pos_y: int

- id: ??
  name: gather
  params:
    - target: int

- id: ??
  name: build
  params:
    - building: int #building ID
    - location_x: int
    - location_y: int

- id: ??
  name: attack_ground
    - target: int